### ISSUE TITLE
Реализовать логирование

### ISSUE THREAD

**Issue by live-HOCOK** [live-HOCOK/CDR_former#24]
иначе непонятно почему не работает

**Comment by Ilnikride** [comment]
Добавил Log4j для логгирования.
Принял за правило что первым параметром передаем уровень логгирования для файлового логгера. Для консольного надо конфигурировать отдельно, по умолчанию для всех выставлен INFO

> Уровни логирование в Log4j выглядят так:
> TRACE
> DEBUG
> INFO
> WARN
> ERROR
> FATAL

Пример использования
`    companion object {
        val logger: Logger = Loggers.fileLogger
    }`
Пример запуска 
`java -jar CDR_former-1.0-SNAPSHOT.jar debug
`
Логи сохраняются в папку logs
