### ISSUE TITLE
Деплоить fat jar

### ISSUE THREAD

**Issue by live-HOCOK** [live-HOCOK/CDR_former#46]
При сборке необходимо деплоить fat jar для того что бы все зависимости были в одном jar

**Comment by live-HOCOK** [comment]
не баг, на всех машинах была проблема с java. Переквалифицировал таску в новую фичу..
добавил fat jar в котором скоплены все зависимости

**Comment by Ilnikride** [comment]
Вроде при сборке проекта все зависимости должны автоматом паковаться в jar, это сломалось?

**Comment by live-HOCOK** [comment]
без папки lib не работает, нужно обязательно было программу использовать с lib. Сейчас она не нужна, только jar
